# Generated by Django 5.1.2 on 2024-11-25 16:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_produto_descricao_alter_produto_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='produto/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'jfif'])]),
        ),
    ]
